spring:
  cloud:
    gateway:
      routes:
        - id: cms_service
          uri: http://localhost:8081
          predicates:
            - Path=/cms/**
          filters:
            - StripPrefix=1

        - id: ros_service
          uri: http://localhost:8082
          predicates:
            - Path=/ros/**

        - id: wms_service
          uri: http://localhost:8083
          predicates:
            - Path=/wms/**
